package carshop_service.constant;

/**
 * Класс, хранящий состояния клиента
 */
public enum ClientState {
    BEGIN_STATE,
    BEGIN_CHOOSE_STATE,
    MENU_CHOOSE_STATE,
    REGISTRATION_STATE,
    AUTHORIZATION_STATE,
    ADMIN_MENU_STATE,
    CLIENT_MENU_STATE,
    MANAGER_MENU_STATE,
    CHOOSE_MAIN_MENU_STATE,
    CLIENT_OUTPUT_MENU_STATE,
    CAR_OUTPUT_MENU_STATE,
    CLIENT_SORT_STATE,
    CLIENT_FILTER_STATE,
    CAR_FILTER_STATE,
    ORDER_OUTPUT_MENU_STATE,
    MAGAZINE_OUTPUT_MENU_STATE,
    ORDER_FILTER_STATE,
    MAGAZINE_FILTER_STATE;
}
